#!/bin/bash

# Function to kill a process given its PID file
kill_process() {
    if [ -f $1 ]; then
        kill -9 $(cat $1)
        rm $1
        echo "Stopped process from $1"
    else
        echo "PID file $1 not found. Process may not be running."
    fi
}

# Stop all servers
kill_process "nextjs.pid"
kill_process "sms-backend.pid"
kill_process "dataApi.pid"

# Stop Docker containers
docker-compose down

echo "All servers have been stopped."

