#!/bin/bash

export CPATH="$HOME/Desktop/clientPackage"

# Print ASCII art
cat << "EOF"
   _____ __  ______    ____  __________  ____  ___________      _____ __________  ___    ____  __________
  / ___//  |/  /   |  / __ \/_  __/ __ )/ __ \/_  __/__  /     / ___// ____/ __ \/   |  / __ \/ ____/ __ \
  \__ \/ /|_/ / /| | / /_/ / / / / __  / / / / / /    / /      \__ \/ /   / /_/ / /| | / /_/ / __/ / /_/ /
 ___/ / /  / / ___ |/ _, _/ / / / /_/ / /_/ / / /    / /__    ___/ / /___/ _, _/ ___ |/ ____/ /___/ _, _/
/____/_/  /_/_/  |_/_/ |_| /_/ /_____/\____/ /_/    /____/   /____/\____/_/ |_/_/  |_/_/   /_____/_/ |_|

EOF

# Create virtual environment and activate it
command virtualenv env

source "$HOME/antiq_scrape/env/bin/activate"


# Install dependencies
pip install -r requirements.txt

# Check if docker-compose is installed
if ! command -v docker-compose &> /dev/null
then
    echo "docker-compose could not be found"
    exit
fi



kill node

# Start Docker containers in the background
docker-compose up -d

# Start the Next.js server in the background and store its PID
(yarn prisma generate && yarn prisma migrate dev && cd "$CPATH/devias-template" && yarn next dev -p 3001) > nextjs.log 2>&1 &
echo $! > nextjs.pid

# Start SMS backend in the background and store its PID
(cd "$CPATH/sms-backend" && yarn run dev:db && yarn run dev) > sms-backend.log 2>&1 &
echo $! > sms-backend.pid

# Start data API server using nodemon in the background and store its PID
node js_bin/dataApi.js > dataApi.log 2>&1 &
echo $! > dataApi.pid


echo "All servers are starting in the background... DO NOT FORGET TO RUN kill_servers!!!!!"
# Print message to test API
echo "----------------------------------------------------------------------"
echo "TEST API WITH"
echo "----------------------------------------------------------------------"

# Print examples
cat ./examples.txt

# Check if npx is installed
if ! command -v npx &> /dev/null
then
    echo "npx could not be found"
    exit
fi

# Start nodemon to run dataApi.js
node js_bin/dataApi.js -p 3002
