#!/usr/bin/env bash
#
#
#
#
echo "Installing Fresh CHromeDriver.."
rm -rf ../../scrapes/build/*
sleep 1
echo "CHromeDriver installed."
echo "Creating Virtualenv.."
virtualenv env && source env/bin/activate
pip install -r requirements.txt
sleep 1
echo " ** FINISHED VIRTUAL ENV ***"
echo "starting servers.."
#
bash ./bin/start.sh




