export const businesses = [
  { id: '1', name: 'Trap Phone' },
  { id: '2', name: 'Gun Store' },
  { id: '3', name: "Crusty Bud's Dispensary" },
  { id: '4', name: 'PissGuy Plumbing' },
  { id: '5', name: 'QuickFix Mechanics' },
];

export const reviews = {
  1: [
    { id: 1, stars: 4, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    {
      id: 2,
      stars: 3,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    {
      id: 3,
      stars: 2,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    { id: 4, stars: 5, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    { id: 5, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    { id: 6, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    { id: 7, stars: 5, userPic: null, review: 'This was a 5 star experience. I would recommend.' },
    {
      id: 8,
      stars: 1,
      userPic: null,
      review: 'This was a 1 star experience. I would not recommend.',
    },
    {
      id: 9,
      stars: 3,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    { id: 10, stars: 4, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
  ],

  2: [
    {
      id: 1,
      stars: 2,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    { id: 2, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    { id: 3, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    { id: 4, stars: 5, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    {
      id: 5,
      stars: 2,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    {
      id: 6,
      stars: 1,
      userPic: null,
      review: 'This was a 1 star experience. I would not recommend.',
    },
    { id: 7, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    { id: 8, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    { id: 9, stars: 5, userPic: null, review: 'This was a 5 star experience. I would recommend.' },
    { id: 10, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
  ],

  3: [
    { id: 1, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    { id: 2, stars: 5, userPic: null, review: 'This was a 5 star experience. I would recommend.' },
    { id: 3, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    {
      id: 4,
      stars: 2,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    { id: 5, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    { id: 6, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    { id: 7, stars: 5, userPic: null, review: 'This was a 5 star experience. I would recommend.' },
    {
      id: 8,
      stars: 1,
      userPic: null,
      review: 'This was a 1 star experience. I would not recommend.',
    },
    {
      id: 9,
      stars: 2,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    { id: 10, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
  ],

  4: [
    { id: 1, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    { id: 2, stars: 5, userPic: null, review: 'This was a 5 star experience. I would recommend.' },
    { id: 3, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    {
      id: 4,
      stars: 1,
      userPic: null,
      review: 'This was a 1 star experience. I would not recommend.',
    },
    {
      id: 5,
      stars: 2,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    { id: 6, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    { id: 7, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    {
      id: 8,
      stars: 2,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    { id: 9, stars: 5, userPic: null, review: 'This was a 5 star experience. I would recommend.' },
    { id: 10, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
  ],

  5: [
    { id: 1, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    { id: 2, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    {
      id: 3,
      stars: 2,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    { id: 4, stars: 5, userPic: null, review: 'This was a 5 star experience. I would recommend.' },
    {
      id: 5,
      stars: 1,
      userPic: null,
      review: 'This was a 1 star experience. I would not recommend.',
    },
    { id: 6, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    {
      id: 7,
      stars: 2,
      userPic: null,
      review: 'This was a 2 star experience. I would not recommend.',
    },
    { id: 8, stars: 4, userPic: null, review: 'This was a 4 star experience. I would recommend.' },
    { id: 9, stars: 3, userPic: null, review: 'This was a 3 star experience. I would recommend.' },
    { id: 10, stars: 5, userPic: null, review: 'This was a 5 star experience. I would recommend.' },
  ],
};

export const chartData = {
  1: [
    { name: 'Jan', views: 2371, clicks: 1928 },
    { name: 'Feb', views: 1563, clicks: 1274 },
    { name: 'Mar', views: 3596, clicks: 1034 },
    { name: 'Apr', views: 1245, clicks: 963 },
    { name: 'May', views: 4163, clicks: 924 },
    { name: 'Jun', views: 4213, clicks: 2875 },
    { name: 'Jul', views: 1423, clicks: 1343 },
    { name: 'Aug', views: 3452, clicks: 1728 },
    { name: 'Sep', views: 4231, clicks: 2371 },
    { name: 'Oct', views: 3533, clicks: 2945 },
    { name: 'Nov', views: 4123, clicks: 2987 },
    { name: 'Dec', views: 2145, clicks: 1294 },
  ],

  2: [
    { name: 'Jan', views: 2145, clicks: 1294 },
    { name: 'Feb', views: 3533, clicks: 2945 },
    { name: 'Mar', views: 4123, clicks: 2987 },
    { name: 'Apr', views: 2371, clicks: 1928 },
    { name: 'May', views: 1563, clicks: 1274 },
    { name: 'Jun', views: 3596, clicks: 1034 },
    { name: 'Jul', views: 1245, clicks: 963 },
    { name: 'Aug', views: 4163, clicks: 924 },
    { name: 'Sep', views: 4213, clicks: 2875 },
    { name: 'Oct', views: 1423, clicks: 1343 },
    { name: 'Nov', views: 3452, clicks: 1728 },
    { name: 'Dec', views: 4231, clicks: 2371 },
  ],

  3: [
    { name: 'Jan', views: 1234, clicks: 876 },
    { name: 'Feb', views: 2345, clicks: 1786 },
    { name: 'Mar', views: 3456, clicks: 1678 },
    { name: 'Apr', views: 4567, clicks: 1965 },
    { name: 'May', views: 5678, clicks: 1854 },
    { name: 'Jun', views: 6789, clicks: 2165 },
    { name: 'Jul', views: 7890, clicks: 1876 },
    { name: 'Aug', views: 8901, clicks: 1687 },
    { name: 'Sep', views: 9012, clicks: 1965 },
    { name: 'Oct', views: 1123, clicks: 1876 },
    { name: 'Nov', views: 2234, clicks: 1687 },
    { name: 'Dec', views: 3345, clicks: 1976 },
  ],

  4: [
    { name: 'Jan', views: 3345, clicks: 1976 },
    { name: 'Feb', views: 1123, clicks: 1876 },
    { name: 'Mar', views: 2234, clicks: 1687 },
    { name: 'Apr', views: 9012, clicks: 1965 },
    { name: 'May', views: 8901, clicks: 1687 },
    { name: 'Jun', views: 7890, clicks: 1876 },
    { name: 'Jul', views: 6789, clicks: 2165 },
    { name: 'Aug', views: 5678, clicks: 1854 },
    { name: 'Sep', views: 4567, clicks: 1965 },
    { name: 'Oct', views: 3456, clicks: 1678 },
    { name: 'Nov', views: 2345, clicks: 1786 },
    { name: 'Dec', views: 1234, clicks: 876 },
  ],

  5: [
    { name: 'Jan', views: 4111, clicks: 3333 },
    { name: 'Feb', views: 2222, clicks: 2222 },
    { name: 'Mar', views: 3333, clicks: 1111 },
    { name: 'Apr', views: 4444, clicks: 2222 },
    { name: 'May', views: 5555, clicks: 3333 },
    { name: 'Jun', views: 1111, clicks: 4444 },
    { name: 'Jul', views: 2222, clicks: 5555 },
    { name: 'Aug', views: 3333, clicks: 1111 },
    { name: 'Sep', views: 4444, clicks: 2222 },
    { name: 'Oct', views: 5555, clicks: 3333 },
    { name: 'Nov', views: 1111, clicks: 4444 },
    { name: 'Dec', views: 2222, clicks: 5555 },
  ],
};
