export const paths = {
  index: '/',
  blank: '/blank',
  dashboard: '/dashboard',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify',
  notFound: '/404',
  serverError: '/500',
  business: '/business',
  trends: 'trends',
  billing: '/billing',
  map: '/map',
  pixel: '/pixel',
  docs: 'docs',
  widget: '/widget',
};
